pokeneas = [
    {
        id: 1,
        name: "Pikachu",
        height: 0.4,
        abilities: "Static",
        image: "https://pokeneas1905.s3.us-east-1.amazonaws.com/pikachu.png",
        phrase: "The unexamined life is not worth living.",
    },
    {
        id: 2,
        name: "Charmander",
        height: 0.6,
        abilities: "Blaze",
        image: "https://pokeneas1905.s3.us-east-1.amazonaws.com/charmander.png",
        phrase: "Happiness depends upon ourselves.",
    },
    {
        id: 3,
        name: "Bulbasaur",
        height: 0.7,
        abilities: "Overgrow",
        image: "https://pokeneas1905.s3.us-east-1.amazonaws.com/bulbasaur.png",
        phrase: "I think, therefore I am.",
    },
    {
        id: 4,
        name: "Squirtle",
        height: 0.5,
        abilities: "Torrent",
        image: "https://pokeneas1905.s3.us-east-1.amazonaws.com/squirtle.png",
        phrase: "He who has a why to live can bear almost any how.",
    },
    {
        id: 5,
        name: "Caterpie",
        height: 0.3,
        abilities: "Shield Dust",
        image: "https://pokeneas1905.s3.us-east-1.amazonaws.com/caterpie.png",
        phrase: "Man is condemned to be free.",
    },
    {
        id: 6,
        name: "Nidoking",
        height: 1.4,
        abilities: "Poison Point",
        image: "https://pokeneas1905.s3.us-east-1.amazonaws.com/nidoking.png",
        phrase: "The only true wisdom is in knowing you know nothing.",
    },
    {
        id: 7,
        name: "Nidoqueen",
        height: 1.3,
        abilities: "Poison Point",
        image: "https://pokeneas1905.s3.us-east-1.amazonaws.com/nidoqueen.png",
        phrase: "Life must be understood backward. But it must be lived forward.",
    },  
    {
        id: 8,
        name: "Clefairy",
        height: 0.6,
        abilities: "Cute Charm",
        image: "https://pokeneas1905.s3.us-east-1.amazonaws.com/clefairy.png",
        phrase: "You only live once, but if you do it right, once is enough.",
    },
    {
        id: 9,
        name: "Jigglypuff",
        height: 0.6,
        abilities: "Cute Charm",
        image: "https://pokeneas1905.s3.us-east-1.amazonaws.com/jigglypuff.png",
        phrase: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
    },
    {
        id: 10,
        name: "Wigglytuff",
        height: 1.0,
        abilities: "Cute Charm",
        image: "https://pokeneas1905.s3.us-east-1.amazonaws.com/wigglytuff.png",
        phrase: "Liberty consists in doing what one desires.",
    },
]   

module.exports = pokeneas;
